// bullswarm connector copies — the `<home>/connectors/<name>.json` files that
// older installs still hold for connectors the package ships.
//
// Doctrine:
//   CC1. Where they come from. Until 0.29.0, `bullswarm setup` copied every
//        packaged connector into <home>/connectors/, and the loader read only
//        those copies. Since 0.29.0 nothing copies them. The packaged provider
//        directories load first, and a copy whose pool one of them defines is
//        skipped as a duplicate (providers.js P3). A copy is read only for a
//        pool no loaded provider defines: a contrib provider that is not
//        enabled, or a pool name the package retired. Every verb still fills
//        newly shipped fields into the copies (setup.js upgradeConnectorMetadata).
//   CC2. An unmodified older copy follows the package. When every field of
//        a copy is a value some packaged version shipped (the provider's
//        connector-history.json), nothing in it is the operator's. It moves to
//        <home>/connectors/retired/ and the packaged connector loads instead.
//        That happens at once when a packaged provider already defines the
//        pool, or by enabling the contrib provider that defines it. Nothing is
//        deleted.
//   CC3. An edited copy is the operator's and is kept. `bullswarm doctor`
//        names its stale fields (those that differ from the package) and says
//        whether the copy is read at all.
//   CC4. A copy with no packaged counterpart is the operator's own local
//        provider. It is never moved or reported.
//   CC5. Zero dependencies; a malformed file or history degrades to "report
//        it, touch nothing".

import { createHash } from 'node:crypto';
import {
  existsSync, mkdirSync, readdirSync, readFileSync, renameSync,
} from 'node:fs';
import { join } from 'node:path';
import { atomicWriteFileSync } from './fsjson.js';
import {
  loadProviders, providersConfigPath, readProvidersConfig, REPO_ROOT,
} from './providers.js';

export const historyFileName = 'connector-history.json';
export const RETIRED_DIR = 'retired';

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (isPlainObject(value)) {
    return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])]));
  }
  return value;
}

/** A short, order-independent (for object keys) fingerprint of one JSON value. */
export function fingerprint(value) {
  return createHash('sha256').update(JSON.stringify(canonical(value)) ?? 'undefined').digest('hex').slice(0, 16);
}

function sameValue(a, b) {
  return fingerprint(a) === fingerprint(b);
}

/**
 * The history document for one connector, from every version it shipped:
 * per top-level field, the fingerprints of each whole value, of each array
 * item, and of each object key's value, and whether some version lacked it.
 * `$comment*` fields are prose and are left out.
 */
export function historyFromVersions(name, versions) {
  const docs = versions.filter(isPlainObject);
  const keys = [...new Set(docs.flatMap((doc) => Object.keys(doc)))]
    .filter((key) => !key.startsWith('$')).sort();
  const fields = {};
  for (const key of keys) {
    const values = new Set();
    const items = new Set();
    const members = {};
    let absent = false;
    for (const doc of docs) {
      if (!Object.hasOwn(doc, key)) { absent = true; continue; }
      const value = doc[key];
      values.add(fingerprint(value));
      if (Array.isArray(value)) for (const item of value) items.add(fingerprint(item));
      else if (isPlainObject(value)) {
        for (const [member, inner] of Object.entries(value)) (members[member] ??= new Set()).add(fingerprint(inner));
      }
    }
    fields[key] = {
      ...(absent ? { absent: true } : {}),
      values: [...values].sort(),
      ...(items.size ? { items: [...items].sort() } : {}),
      ...(Object.keys(members).length ? {
        keys: Object.fromEntries(Object.keys(members).sort().map((member) => [member, [...members[member]].sort()])),
      } : {}),
    };
  }
  return {
    $comment: 'Generated by scripts/connector-history.mjs: fingerprints of every value each field of this connector has shipped with, the flat connectors/ file before 0.29.0 included. src/lib/connector-copies.js uses it to tell an unmodified older copy in <home>/connectors/ from an edited one. Regenerate after changing connector.json.',
    connector: name,
    fields,
  };
}

/**
 * Every packaged connector a `<home>/connectors/<name>.json` copy can
 * belong to: one per provider directory in the first-class and contrib
 * tiers, matched by the directory name, as the old flat files were named.
 */
export function packagedConnectorSources({ repoRoot = REPO_ROOT } = {}) {
  const out = [];
  for (const [tier, base] of [
    ['first-class', join(repoRoot, 'src', 'providers')],
    ['contrib', join(repoRoot, 'providers', 'contrib')],
  ]) {
    if (!existsSync(base)) continue;
    for (const name of readdirSync(base).sort()) {
      if (name.startsWith('_') || name.startsWith('.')) continue;
      const connector = join(base, name, 'connector.json');
      if (existsSync(connector)) out.push({ file: `${name}.json`, name, tier, dir: join(base, name), connector });
    }
  }
  return out;
}

function readHistory(dir) {
  try {
    const history = JSON.parse(readFileSync(join(dir, historyFileName), 'utf8'));
    return isPlainObject(history?.fields) ? history : { fields: {} };
  } catch {
    return { fields: {} };
  }
}

/** Did some packaged version ship this value for this field (CC2)? */
function shippedValue(record, value) {
  if (!record) return false;
  const has = (list, item) => Array.isArray(list) && list.includes(fingerprint(item));
  if (has(record.values, value)) return true;
  // A fill-only upgrade merges packaged items and keys into a copy, so a
  // merged value counts when each of its parts shipped somewhere.
  if (Array.isArray(value) && value.length) return value.every((item) => has(record.items, item));
  if (isPlainObject(value) && Object.keys(value).length) {
    return Object.entries(value).every(([member, inner]) => has(record.keys?.[member], inner));
  }
  return false;
}

/**
 * The fields of a copy that differ from the packaged connector, split into
 * `staleFields` (an older packaged value, or a field the package added since)
 * and `editedFields` (a value no packaged version had, or a field removed that
 * every version shipped).
 */
export function compareCopy(copy, packaged, history = { fields: {} }) {
  const staleFields = [];
  const editedFields = [];
  const keys = [...new Set([...Object.keys(copy ?? {}), ...Object.keys(packaged ?? {})])]
    .filter((key) => !key.startsWith('$')).sort();
  for (const key of keys) {
    const inCopy = Object.hasOwn(copy ?? {}, key);
    if (inCopy && Object.hasOwn(packaged ?? {}, key) && sameValue(copy[key], packaged[key])) continue;
    const record = history.fields?.[key];
    const older = inCopy ? shippedValue(record, copy[key]) : record?.absent === true;
    (older ? staleFields : editedFields).push(key);
  }
  return { staleFields, editedFields };
}

/**
 * Every copy in `<home>/connectors/` that has a packaged counterpart, with:
 *   status        current | older-copy | edited | unreadable
 *   staleFields   fields where the copy holds an older packaged value
 *   editedFields  fields that are the operator's own
 *   read          whether the loader uses this copy for its pool
 *   servedBy      the packaged provider that defines the pool instead, or null
 *
 * `opts.loader` reaches loadProviders; `opts.repoRoot` the packaged sources.
 */
export function inspectConnectorCopies(bullswarmDir, opts = {}) {
  const dir = join(bullswarmDir, 'connectors');
  if (!existsSync(dir)) return [];
  const sources = new Map(packagedConnectorSources(opts).map((source) => [source.file, source]));
  let files = [];
  try {
    files = readdirSync(dir).sort().filter((file) => file.endsWith('.json') && sources.has(file));
  } catch { return []; }
  if (!files.length) return [];
  const loaded = loadProviders(bullswarmDir, opts.loader ?? {});
  const copies = [];
  for (const file of files) {
    const source = sources.get(file);
    const path = join(dir, file);
    const base = { file, path, provider: source.name, tier: source.tier };
    let copy;
    let packaged;
    try {
      copy = JSON.parse(readFileSync(path, 'utf8'));
      packaged = JSON.parse(readFileSync(source.connector, 'utf8'));
    } catch (err) {
      copies.push({ ...base, pool: null, status: 'unreadable', error: err.message, staleFields: [], editedFields: [], read: false, servedBy: null });
      continue;
    }
    const { staleFields, editedFields } = compareCopy(copy, packaged, readHistory(source.dir));
    const pool = typeof copy?.name === 'string' ? copy.name : null;
    const entry = loaded.providers.find((provider) => provider.dir === path);
    const owner = pool
      ? loaded.providers.find((provider) => provider !== entry && provider.pools.includes(pool))
      : null;
    copies.push({
      ...base,
      pool,
      status: editedFields.length ? 'edited' : staleFields.length ? 'older-copy' : 'current',
      staleFields,
      editedFields,
      read: Boolean(entry?.pools.includes(pool)),
      servedBy: owner?.name ?? null,
    });
  }
  return copies;
}

function retire(bullswarmDir, copy) {
  const target = join(bullswarmDir, 'connectors', RETIRED_DIR);
  mkdirSync(target, { recursive: true });
  let destination = join(target, copy.file);
  if (existsSync(destination)) {
    destination = join(target, copy.file.replace(/\.json$/, `.${Date.now()}.json`));
  }
  renameSync(copy.path, destination);
  return destination;
}

/**
 * CC2: retire every unmodified older copy, so the packaged connector is what
 * loads. Returns one action per retired copy; edited, current and unreadable
 * copies are left exactly as they are.
 */
export function syncConnectorCopies(bullswarmDir, opts = {}) {
  const actions = [];
  for (const copy of inspectConnectorCopies(bullswarmDir, opts)) {
    if (copy.status !== 'older-copy') continue;
    try {
      if (copy.servedBy) {
        actions.push({ file: copy.file, action: 'retired', servedBy: copy.servedBy, to: retire(bullswarmDir, copy) });
        continue;
      }
      // Only the copy defines the pool today. A contrib provider takes it
      // over once enabled, provided it really defines a pool of that name.
      if (copy.tier !== 'contrib' || !copy.read) continue;
      const config = readProvidersConfig(bullswarmDir);
      const enabled = [...new Set([...config.enabled, copy.provider])];
      const trial = loadProviders(bullswarmDir, { ...(opts.loader ?? {}), enabled });
      const contrib = trial.providers.find((provider) => provider.tier === 'contrib' && provider.name === copy.provider);
      if (!contrib?.pools.includes(copy.pool)) continue;
      atomicWriteFileSync(providersConfigPath(bullswarmDir), `${JSON.stringify({ ...config, enabled }, null, 2)}\n`);
      actions.push({
        file: copy.file, action: 'retired', servedBy: copy.provider, enabledProvider: copy.provider,
        to: retire(bullswarmDir, copy),
      });
    } catch { /* CC5: a copy that cannot be moved stays and is reported */ }
  }
  return actions;
}

/** The copies earlier syncs retired (`<home>/connectors/retired/*.json`). */
export function retiredConnectorCopies(bullswarmDir) {
  const dir = join(bullswarmDir, 'connectors', RETIRED_DIR);
  try {
    return readdirSync(dir).filter((file) => file.endsWith('.json')).sort();
  } catch {
    return [];
  }
}

/** One plain line per copy that needs the operator's eye (CC3), for doctor and strategy show. */
export function connectorCopyWarnings(copies) {
  return copies.filter((copy) => copy.status === 'edited' || copy.status === 'unreadable' || copy.status === 'older-copy')
    .map((copy) => {
      if (copy.status === 'unreadable') return `${copy.path}: not valid JSON (${copy.error}); left as it is`;
      const where = copy.read
        ? `still read for pool ${copy.pool}`
        : copy.servedBy ? `not read; the packaged ${copy.servedBy} connector loads instead` : 'not read';
      if (copy.status === 'older-copy') {
        return `${copy.path}: unmodified older copy, ${where}; stale: ${copy.staleFields.join(', ')}`;
      }
      const stale = copy.staleFields.length ? `stale: ${copy.staleFields.join(', ')}` : 'no stale fields';
      return `${copy.path}: your edited copy, kept (edited: ${copy.editedFields.join(', ')}); ${stale}; ${where}`;
    });
}
